### ISSUE TITLE
Project Renaming is now Supported by Self XDSD

### ISSUE THREAD

**Issue by amihaiemil** [fedorpashin/Tabella#8]
Hi @fedorpashin 

Just wanted to let you know that Self XDSD supports repo renaming now.

This will work out of the box for repos you register from now on, but for repos which are already registered, you have to go to the Self XDSD Webhook (Settings -> Webhooks -> https://self-xdsd.com/...) and check the ``Repositories`` combobox and click "Update Webhook".

<img width="336" alt="Screenshot 2021-09-02 at 15 03 50" src="https://user-images.githubusercontent.com/6305156/131840601-d68b08a7-6c5e-4a1e-8ebb-0278a17a8c10.png">

This is because Self XDSD cannot modify webhooks once the project is registered.

Have fun :D

**Comment by zoeself** [comment]
@amihaiemil thank you for reporting this. I'll assign someone to take care of it soon.
